### ISSUE TITLE
Move & split up SpaceAPi related code

### ISSUE THREAD

**Issue by dbrgn** [coredump-ch/spaceapi#22]
We should move all API type related stuff to a separate crate. It should contain the following:

- Easy way to create a strictly typed `spaceapi::Status` instance
- Easy way to convert it to a string
- Separate files for different parts of the API types. The `src/spaceapi.rs` file got quite large. Either we split up type structs and `ToJson` implementations, or we split up according to categories (like properties, features, mutable etc).

This should be a separate crate that could be uploaded to crates.io.

@rnestler opinions?

**Comment by rnestler** [comment]
How do you want do do the crate split?
 * Separate repo
 * http://doc.crates.io/guide.html#path-dependencies

**Comment by dbrgn** [comment]
I'd do path dependencies in a single repo. I already started working on a draft on my laptop, that's why I "claimed" this thicket :)

**Comment by dbrgn** [comment]
Or do you think multiple repos would be better?

**Comment by rnestler** [comment]
If we consider 3rd party usage of our spaceapi lib than maybe a separate repository would be better. Otherwise they end up with coredump specific stuff. But if we upload it to crates.io I think this is a non-issue.

**Comment by dbrgn** [comment]
Yes, I'd keep it together on Github until we completely separated our stuff from the generic parts.

**Comment by dbrgn** [comment]
What about #26? We can then build upon that to get even better separation. Maybe also do a clean API design with a few `pub use` commands.

**Comment by dbrgn** [comment]
After today's discussion:

- Two crates: `spaceapi` and `spaceapi-server`
- User will depend on `spaceapi-server`
- The server exposes the spaceapi data structures with `pub use`
- The `spaceapi` create holds the data definitions and does serialization
- The server calls `to_json()` on the `Status` object

**Comment by rnestler** [comment]
I think we closed this with #26

**Comment by dbrgn** [comment]
Not yet, the goal is reached as soon as we don't have anything coredump-specific in the spaceapi_server crate :)

**Comment by dbrgn** [comment]
The current idea: The user registers a sensor (omitting the value) together with the key that can be used to retrieve the actual value from the datastore.

The problem here is that a value is a required field in a sensor object, so it cannot be omitted.

What could we do here? An approach would be to create a new arithmetic datatype `DelayedField<T> { Present<T>, Undetermined }` that can be used in this case. If it's `Undetermined`, then serialization would cause a problem.

The downside of tihs is that it makes the API of the `spaceapi` crate a little bit more ugly / complex :) Other ideas? @rnestler

**Comment by rnestler** [comment]
I think we should differentiate between the sensors registered to be retrieved from the datastore and the sensors that will get serialized to json. I would leave the types in ``spaceapi / src / lib.rs`` as they are right now. The target for these types is, that they *always* serialize to valid SpaceAPI data.

**Comment by dbrgn** [comment]
Done :sparkles:
