### ISSUE TITLE
Implement PeopleNowPresentSensor Service

### ISSUE THREAD

**Issue by dbrgn** [coredump-ch/spaceapi#23]
Service to update "people now present" sensor.

Blocked by #22.

@rnestler can you do this one?

**Comment by rnestler** [comment]
@dbrgn Sure I can do this one

**Comment by rnestler** [comment]
So this is actually two tasks. Implementing a daemon that collects the data from the sensor and implementing the API in the main server to receive new values.

**Comment by dbrgn** [comment]
Exactly!

**Comment by dbrgn** [comment]
Closed, we'll do a monolithing key-value updating thing in the spaceapi_server crate.
