### ISSUE TITLE
Persist data

### ISSUE THREAD

**Issue by dbrgn** [coredump-ch/spaceapi#4]
We should be able to store and read data from the filesystem.

Maybe there's some simple kind of serialization format? Or SQLite?

**Comment by dbrgn** [comment]
Good question. What we lose is the `last_changed` information. The rest would/should be updated by the sensor every 10-30 seconds.

**Comment by dbrgn** [comment]
What about serialization to JSON and then writing it to a file?

**Comment by dbrgn** [comment]
Hm, then we have problems with race conditions (a worker process writing the file while another one reads it).

We could move to threading, but then the server is not parallelizable across multiple hosts. So the over-engineering nerd in me would suggest either Redis or ZeroMQ.

**Comment by dbrgn** [comment]
Started redis branch here: https://github.com/coredump-ch/spaceapi/tree/redis. See https://github.com/coredump-ch/spaceapi/commit/f90dc424a357b1bc203056f8caba70f39ab149f5

**Comment by rnestler** [comment]
We could use redis as data storage for both the python and the rust implementation. Btw. I added a README on how to use redis with 82699e9e69148c9643e5cc1778d6606662fbe130, since I had to figure it out first.

**Comment by dbrgn** [comment]
> We could use redis as data storage for both the python and the rust implementation.

True! Although I would not continue developing the Python version.

> I added a README on how to use redis with 82699e9, since I had to figure it out first.

Good, thanks. Other useful commands are "GET <key>" and "KEYS *".

**Comment by rnestler** [comment]
Closed with 4df83691eabab87793d259142e59ba151fcb1b0d
