### ISSUE TITLE
Implement unwrap() for `Optional`

### ISSUE THREAD

**Issue by dbrgn** [coredump-ch/spaceapi#41]
Like with the Option, retrieve the value or panic.

@rnestler I couldn't manage to get it to work, due to lifetimes, maybe you can? :)

**Comment by rnestler** [comment]
Where would you use it? I'm not a huge fan of ``unwrap()`` and runtime panics...

**Comment by dbrgn** [comment]
```rust
if value.is_some() {
    ...
    let val = value.unwrap();
```

Also, to be closer to `Option`.

**Comment by dbrgn** [comment]
Apparently I could get rid of the case where I used unnecessary `match`es in #42, so we could wait with this implementation until there's an actual use case for it.

**Comment by rnestler** [comment]
There was a usecase in 12ff5becc77b26e5231d36d90644a1c61790dab1 so it was implemented in 6030639a35e70007a1fd337cdb03b7f6b579852c
