### ISSUE TITLE
Implement people_now_present -> Open state

### ISSUE THREAD

**Issue by rnestler** [coredump-ch/spaceapi#53]
In the python script we have the people_now_present sensor connected to the Open state. We should implement this in Rust as well

**Comment by dbrgn** [comment]
Yep.

In the first step, I'd simply hardcode that connection. In a second step we could try to make it configurable.

**Comment by dbrgn** [comment]
I think we could close that for now, fixed in #54.

**Comment by rnestler** [comment]
So be it.
