### ISSUE TITLE
Configurable port

### ISSUE THREAD

**Issue by dbrgn** [coredump-ch/spaceapi#6]
Would be nice if the port could be configured at compiletime or at runtime.

**Comment by rnestler** [comment]
What do you mean be "configured at compiletime" It can be changed at compiletime by changing ``let port = 3000;`` At runtime would probably be command line arguments or a configfile

**Comment by dbrgn** [comment]
Hehe, true. I was thinking about something like an `ifdef` in C combined with a compilation parameter.

Is there some way to pass parameters to cargo?

**Comment by rnestler** [comment]
http://doc.crates.io/build-script.html looks interesting

**Comment by rnestler** [comment]
With the merge I consider this closed
